name: Build ipk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4
        with:
          ref: po

      - name: Build ipk file
        env:
          RELEASE_TYPE: ${{ github.event_name }}
        run: |
          pushd .github
          fakeroot bash build-ipk.sh
          echo "ASSET_NAME=$(ls *.ipk)" >> $GITHUB_ENV
          popd

      - name: Publishing to GitHub Artifacts
        uses: actions/upload-artifact@v4
        if: github.event_name != 'release'
        with:
          name: ${{ env.ASSET_NAME }}
          path: .github/${{ env.ASSET_NAME }}

      - name: Publishing to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ github.token }}
          file: .github/${{ env.ASSET_NAME }}
          tag: ${{ github.ref }}
